version: '3'

services:
  wormhole:
    image: miraz4300/wormhole:latest
    container_name: wormhole
    restart: always
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      #- WARP_LICENSE_KEY= # optional & required for warp+
      - NETBIRD_MGNT_URL=
      - NETBIRD_SETUP_KEY=
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wormhole-data:/var/lib/cloudflare-warp

volumes:
  wormhole-data:
