version: '3'

services:
  wormhole:
    image: miraz4300/wormhole:latest
    container_name: wormhole
    privileged: true
    restart: always
    ports:
      - '1080:1080'
    environment:
      #- WARP_LICENSE_KEY= # optional & required for warp+
      - NETBIRD_MGMT_URL=
      - NETBIRD_SETUP_KEY=
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wormhole-warp:/var/lib/cloudflare-warp
      - wormhole-netbird:/var/lib/docker

volumes:
  wormhole-warp:
  wormhole-netbird:
